version: '3.9'

networks:
  threads:
    external: true

services:
  threads-core:
    build:
      context: .
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - threads
    env_file:
      - .env
    restart: always